/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all projects
         * @description List all projects
         */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /**
         * Create a new project
         * @description Create a new project
         */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a project by id
         * @description Get a project by id
         */
        get: operations["get_project_v1_projects__project_id__get"];
        /**
         * Update a project by id
         * @description Update a project by id
         */
        put: operations["update_project_v1_projects__project_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a project by id
         * @description Archive a project by id
         */
        post: operations["archive_project_v1_projects__project_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all chats
         * @description List all chats
         */
        get: operations["list_chats_v1_chats_get"];
        put?: never;
        /**
         * Create a new chat
         * @description Create a new project
         */
        post: operations["create_chat_v1_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a chat by id
         * @description Get a chat by id
         */
        get: operations["get_chat_v1_chats__chat_id__get"];
        /**
         * Update a chat by id
         * @description Update a chat by id
         */
        put: operations["update_chat_v1_chats__chat_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chats/{chat_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a chat by id
         * @description Archive a chat by id
         */
        post: operations["archive_chat_v1_chats__chat_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List messages in a chat
         * @description List all messages in a chat with sources
         */
        get: operations["list_chat_messages_v1_chats__chat_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chats/{chat_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a streaming message to a chat
         * @description Send a message to a chat with streaming response
         */
        post: operations["send_streaming_message_v1_chats__chat_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a document
         * @description Upload and process a document for the project
         */
        post: operations["upload_document_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all documents
         * @description List all documents for a project
         */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a document by id
         * @description Get a document by id
         */
        get: operations["get_document_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview a document
         * @description Stream document content for preview in browser
         */
        get: operations["preview_document_v1_documents__document_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List flashcard groups
         * @description List all flashcard groups for a project
         */
        get: operations["list_flashcard_groups_v1_flashcards_get"];
        put?: never;
        /**
         * Create a flashcard group
         * @description Create a new flashcard group for a project, optionally with generated flashcards
         */
        post: operations["create_flashcard_group_v1_flashcards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flashcards/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flashcard group
         * @description Get a specific flashcard group by ID
         */
        get: operations["get_flashcard_group_v1_flashcards__group_id__get"];
        /**
         * Update flashcard group
         * @description Update a flashcard group
         */
        put: operations["update_flashcard_group_v1_flashcards__group_id__put"];
        post?: never;
        /**
         * Delete flashcard group
         * @description Delete a flashcard group and all its flashcards
         */
        delete: operations["delete_flashcard_group_v1_flashcards__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flashcards/{group_id}/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List flashcards
         * @description List all flashcards in a group
         */
        get: operations["list_flashcards_v1_flashcards__group_id__flashcards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List quizzes
         * @description List all quizzes for a project
         */
        get: operations["list_quizzes_v1_quizzes_get"];
        put?: never;
        /**
         * Create a quiz
         * @description Create a new quiz for a project, optionally with generated questions
         */
        post: operations["create_quiz_v1_quizzes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get quiz
         * @description Get a specific quiz by ID
         */
        get: operations["get_quiz_v1_quizzes__quiz_id__get"];
        /**
         * Update quiz
         * @description Update a quiz
         */
        put: operations["update_quiz_v1_quizzes__quiz_id__put"];
        post?: never;
        /**
         * Delete quiz
         * @description Delete a quiz and all its questions
         */
        delete: operations["delete_quiz_v1_quizzes__quiz_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quizzes/{quiz_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List quiz questions
         * @description List all questions in a quiz
         */
        get: operations["list_quiz_questions_v1_quizzes__quiz_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get authenticated user information (requires auth)
         */
        get: operations["get_current_user_info_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Simple health check that doesn't require database
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_v1_documents_upload_post */
        Body_upload_document_v1_documents_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * ChatCompletionRequest
         * @description Request model for chat completion with RAG.
         */
        ChatCompletionRequest: {
            /**
             * Message
             * @description User message to process
             */
            message: string;
        };
        /**
         * ChatCreateRequest
         * @description Request model for creating a new chat.
         */
        ChatCreateRequest: {
            /**
             * Project Id
             * @description ID of the project this chat belongs to
             */
            project_id: string;
        };
        /**
         * ChatDto
         * @description Response model for chat data.
         */
        ChatDto: {
            /**
             * Id
             * @description Unique ID of the chat
             */
            id: string;
            /**
             * Project Id
             * @description ID of the project this chat belongs to
             */
            project_id: string;
            /**
             * User Id
             * @description ID of the user who created the chat
             */
            user_id: string;
            /**
             * Title
             * @description Title of the chat
             */
            title: string | null;
            /**
             * Messages
             * @description List of messages in the chat
             */
            messages?: components["schemas"]["ChatMessageDto"][];
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * ChatListResponse
         * @description Response model for listing chats.
         */
        ChatListResponse: {
            /**
             * Data
             * @description List of chats
             */
            data: components["schemas"]["ChatDto"][];
            /**
             * Total Count
             * @description Total number of chats
             */
            total_count: number;
        };
        /**
         * ChatMessageDto
         * @description Response model for chat message data.
         */
        ChatMessageDto: {
            /**
             * Id
             * @description Unique ID of the message
             */
            id: string;
            /**
             * Role
             * @description Role of the message sender
             */
            role: string;
            /**
             * Content
             * @description Content of the message
             */
            content: string;
            /**
             * Sources
             * @description Source documents for assistant messages
             */
            sources?: components["schemas"]["SourceDto"][] | null;
            /**
             * Tools
             * @description Tool calls made during message generation
             */
            tools?: components["schemas"]["ToolCallDto"][] | null;
        };
        /**
         * ChatUpdateRequest
         * @description Request model for updating a chat.
         */
        ChatUpdateRequest: {
            /**
             * Title
             * @description Title of the chat
             */
            title?: string | null;
        };
        /**
         * CreateFlashcardGroupRequest
         * @description Request model for creating a flashcard group.
         */
        CreateFlashcardGroupRequest: {
            /**
             * Flashcard Count
             * @description Number of flashcards to generate
             * @default 30
             */
            flashcard_count: number;
            /**
             * User Prompt
             * @description Custom prompt to enhance generation
             */
            user_prompt?: string | null;
        };
        /**
         * CreateQuizRequest
         * @description Request model for creating a quiz.
         */
        CreateQuizRequest: {
            /**
             * Question Count
             * @description Number of quiz questions to generate
             * @default 30
             */
            question_count: number;
            /**
             * User Prompt
             * @description Custom prompt to enhance generation
             */
            user_prompt?: string | null;
        };
        /** DocumentDto */
        DocumentDto: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Project Id */
            project_id: string | null;
            /** File Name */
            file_name: string;
            /** File Type */
            file_type: string;
            /** File Size */
            file_size: number;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Processed At */
            processed_at: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Data */
            data: components["schemas"]["DocumentDto"][];
            /** Total Count */
            total_count: number;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /** Document Id */
            document_id: string;
        };
        /**
         * FlashcardDto
         * @description Flashcard data transfer object.
         */
        FlashcardDto: {
            /** Id */
            id: string;
            /** Group Id */
            group_id: string;
            /** Project Id */
            project_id: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Difficulty Level */
            difficulty_level: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FlashcardGroupDto
         * @description Flashcard group data transfer object.
         */
        FlashcardGroupDto: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FlashcardGroupListResponse
         * @description Response model for listing flashcard groups.
         */
        FlashcardGroupListResponse: {
            /** Data */
            data: components["schemas"]["FlashcardGroupDto"][];
            /** Total */
            total: number;
        };
        /**
         * FlashcardGroupResponse
         * @description Response model for flashcard group operations.
         */
        FlashcardGroupResponse: {
            flashcard_group: components["schemas"]["FlashcardGroupDto"];
            /** Message */
            message: string;
        };
        /**
         * FlashcardListResponse
         * @description Response model for listing flashcards.
         */
        FlashcardListResponse: {
            /** Flashcards */
            flashcards: components["schemas"]["FlashcardDto"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProjectCreateRequest
         * @description Request model for creating a new project.
         */
        ProjectCreateRequest: {
            /**
             * Name
             * @description Name of the project
             */
            name: string;
            /**
             * Description
             * @description Description of the project
             */
            description?: string | null;
            /**
             * Language Code
             * @description Language code (e.g., 'en', 'es', 'fr')
             * @default en
             */
            language_code: string | null;
        };
        /**
         * ProjectDto
         * @description Response model for project data.
         */
        ProjectDto: {
            /**
             * Id
             * @description Unique ID of the project
             */
            id: string;
            /**
             * Owner Id
             * @description ID of the project owner
             */
            owner_id: string;
            /**
             * Name
             * @description Name of the project
             */
            name: string;
            /**
             * Description
             * @description Description of the project
             */
            description: string | null;
            /**
             * Language Code
             * @description Language code
             */
            language_code: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /**
         * ProjectListResponse
         * @description Response model for listing projects.
         */
        ProjectListResponse: {
            /**
             * Data
             * @description List of projects
             */
            data: components["schemas"]["ProjectDto"][];
            /**
             * Total Count
             * @description Total number of projects
             */
            total_count: number;
        };
        /**
         * ProjectUpdateRequest
         * @description Request model for updating a project.
         */
        ProjectUpdateRequest: {
            /**
             * Name
             * @description Name of the project
             */
            name?: string | null;
            /**
             * Description
             * @description Description of the project
             */
            description?: string | null;
            /**
             * Language Code
             * @description Language code (e.g., 'en', 'es', 'fr')
             */
            language_code?: string | null;
        };
        /**
         * QuizDto
         * @description Quiz data transfer object.
         */
        QuizDto: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * QuizListResponse
         * @description Response model for listing quizzes.
         */
        QuizListResponse: {
            /** Data */
            data: components["schemas"]["QuizDto"][];
            /** Total */
            total: number;
        };
        /**
         * QuizQuestionDto
         * @description Quiz question data transfer object.
         */
        QuizQuestionDto: {
            /** Id */
            id: string;
            /** Quiz Id */
            quiz_id: string;
            /** Project Id */
            project_id: string;
            /** Question Text */
            question_text: string;
            /** Option A */
            option_a: string;
            /** Option B */
            option_b: string;
            /** Option C */
            option_c: string;
            /** Option D */
            option_d: string;
            /** Correct Option */
            correct_option: string;
            /** Explanation */
            explanation?: string | null;
            /** Difficulty Level */
            difficulty_level: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * QuizQuestionListResponse
         * @description Response model for listing quiz questions.
         */
        QuizQuestionListResponse: {
            /** Quiz Questions */
            quiz_questions: components["schemas"]["QuizQuestionDto"][];
            /** Total */
            total: number;
        };
        /**
         * QuizResponse
         * @description Response model for quiz operations.
         */
        QuizResponse: {
            quiz: components["schemas"]["QuizDto"];
            /** Message */
            message: string;
        };
        /**
         * SourceDto
         * @description Response model for source document data.
         */
        SourceDto: {
            /**
             * Id
             * @description Unique ID of the source segment
             */
            id: string;
            /**
             * Citation Index
             * @description Citation number for [n] references
             */
            citation_index: number;
            /**
             * Content
             * @description Content of the source segment
             */
            content: string;
            /**
             * Title
             * @description Title/name of the source document
             */
            title: string;
            /**
             * Document Id
             * @description ID of the source document
             */
            document_id: string;
            /**
             * Preview Url
             * @description URL to preview/download the document
             */
            preview_url?: string | null;
            /**
             * Score
             * @description Relevance score of the source
             */
            score: number;
        };
        /**
         * ToolCallDto
         * @description Response model for tool call data.
         */
        ToolCallDto: {
            /**
             * Id
             * @description Unique ID of the tool call
             */
            id: string;
            /**
             * Type
             * @description Tool type identifier
             */
            type: string;
            /**
             * Name
             * @description Name of the tool being called
             */
            name: string;
            /**
             * State
             * @description Current state of the tool call
             * @enum {string}
             */
            state: "input-streaming" | "input-available" | "output-available" | "output-error";
            /**
             * Input
             * @description Input parameters for the tool
             */
            input?: {
                [key: string]: unknown;
            } | null;
            /**
             * Output
             * @description Output result from the tool
             */
            output?: unknown | null;
            /**
             * Error Text
             * @description Error message if failed
             */
            error_text?: string | null;
        };
        /**
         * UpdateFlashcardGroupRequest
         * @description Request model for updating a flashcard group.
         */
        UpdateFlashcardGroupRequest: {
            /**
             * Name
             * @description Name of the flashcard group
             */
            name?: string | null;
            /**
             * Description
             * @description Description of the flashcard group
             */
            description?: string | null;
        };
        /**
         * UpdateQuizRequest
         * @description Request model for updating a quiz.
         */
        UpdateQuizRequest: {
            /**
             * Name
             * @description Name of the quiz
             */
            name?: string | null;
            /**
             * Description
             * @description Description of the quiz
             */
            description?: string | null;
        };
        /** UserDto */
        UserDto: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Azure Oid */
            azure_oid: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_v1_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project_v1_projects__project_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_v1_chats_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_v1_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_v1_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_v1_chats__chat_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_chat_v1_chats__chat_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_messages_v1_chats__chat_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageDto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_streaming_message_v1_chats__chat_id__messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_v1_documents_upload_post: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_document_v1_documents__document_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flashcard_groups_v1_flashcards_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardGroupListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_flashcard_group_v1_flashcards_post: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFlashcardGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_flashcard_group_v1_flashcards__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flashcard group ID */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_flashcard_group_v1_flashcards__group_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flashcard group ID */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateFlashcardGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_flashcard_group_v1_flashcards__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flashcard group ID */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flashcards_v1_flashcards__group_id__flashcards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flashcard group ID */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quizzes_v1_quizzes_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_quiz_v1_quizzes_post: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_v1_quizzes__quiz_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz ID */
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quiz_v1_quizzes__quiz_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz ID */
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateQuizRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_quiz_v1_quizzes__quiz_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz ID */
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quiz_questions_v1_quizzes__quiz_id__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Quiz ID */
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizQuestionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
